spring.datasource.url=jdbc:postgresql://dpg-d8b9f5cm0tmc73dbng20-a.singapore-postgres.render.com:5432/teamb
spring.datasource.username=teamb
spring.datasource.password=0bTwCJ8SAkMhjKFdWhZND9SXSYI4KCdl

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
